/rus_sim_planner:
  ros__parameters:
    # 话题，服务相关的参数
    point_cloud_topic: "/preprocessed_cloud"
    init_service: "init_planner"
    planner_service: "generate_trajectory"

    # 规划器初始化所需参数
    alpha: 1.0          # 椭圆 Gabriel 条件检查参数
    graph_k: 30         # 构建初始图的 k-NN 参数
    normal_k: 30        # 法线估计的参数
    projection_k: 30    # 重投影的参数
    tol: 1.0e-6         # 长度变化容差
    max_iter: 40        # 最大迭代轮次
    use_smoothing: true # 是否开启平滑
    lambda: 0.63       # 平滑参数
    mu: -0.65           # 平滑参数
    
    # 偏移量
    flange_offset: 0.0938  # 法兰相对TF树末端的Z轴方向的偏移量，单位米
    # 法兰到探头的变换矩阵
    probe_to_flange: [0.452362, 0.0830591, 0.887958, 0.00492813,
                      0.891303, -0.00774884, -0.453341, 0.00274416,
                      -0.0307735, 0.996514, -0.0775361, 0.217645,
                      0.0, 0.0, 0.0]  # 少了个1.0，现用于测试