# 点云数据处理节点参数配置
/rus_sim_cloud:
  ros__parameters:
    # 话题名称参数
    input_cloud_topic: "/camera/camera/depth/color/points"       # 输入点云话题，输入原始点云数据
    output_cloud_topic: "/preprocessed_cloud"     # 输出点云话题，输出预处理后的点云
    robot_pose_topic: "/nonrt_state_data"   # 机器人位姿话题
    end_pose_topic: "/end_pose"
    cmd_service: "pre_sacn_cmd"              # 预扫查指令服务名称

    # 时间同步参数
    max_allowed_diff_sec: 0.05              # 点云与位姿的最大允许时间差（秒）

    # 缓存参数
    max_cache_size: 50                      # 最大缓存点云帧数

    # 点云的采样周期，单位为秒
    cloud_sample_period: 2.

    # -------------------- 预处理滤波器参数 --------------------
    # 体素滤波参数
    voxel_leaf_size: 0.003                  # 体素滤波器叶子大小（米）

    # 直通滤波参数
    passthrough_field: "z"                  # 直通滤波字段，可选 "x", "y", "z"
    passthrough_limit_min: -0.5             # 直通滤波最小值
    passthrough_limit_max: 0.5              # 直通滤波最大值
    passthrough_negative: false             # 是否取反（提取范围外的点）

    # 统计滤波参数
    statistical_mean_k: 50                  # 统计滤波邻域点数
    statistical_std_dev_mul: 1.0            # 统计滤波标准差倍数

    # 标定后的相机相对机械臂末端的变换矩阵
    camera_to_end: [
      -0.6890016, 0.72474778, -0.00417675, 0.09376472,
      -0.72475632, -0.68896894, 0.00707673, -0.03569825,
      0.0022512, 0.00790301, 0.99996624, -0.04231331,
      0.0, 0.0, 0.0, 1.0]